#FROM python:3.8-slim
#RUN python -m pip install --upgrade pip
#COPY . /app
#WORKDIR /app
#RUN pip install -r requirements.txt
## COPY pem/global-bundle.pem /app/pem/global-bundle.pem
## RUN flask db init
## RUN flask db migrate
## RUN flask db upgrade
## ENTRYPOINT ["python"]
## CMD ["application.py"]
## CMD ["gunicorn", "-w", "4", "-k", "gevent", "-b", "0.0.0.0:8051", "application:app"]
#CMD ["gunicorn", "-w", "4", "-k", "gevent", "-b", "0.0.0.0:8051", "--config", "gunicorn_config.py", "application:app"]
